### PR TITLE
API V3 Compliance

### LINKED ISSUE #130: Move to v3

### PR DESCRIPTION
**Pull request by maxdumas**
Finally got around to looking into this… Sorry for the big diff, a lot of it is linting/style check compliance. This PR may have additional updates, still fishing around for bugs.

This incorporates @ethanresnick's changes from #131. Resolves #130.

@ethanresnick @brentdur it looks like `maxlength` is not being reported on any fields that had it before, so nothing is using TinyMCE right now because a `maxlength` validation attribute of at least 140 is a prerequisite for using it. That's probably why things are working fine right now. :) 

@AbhiAgarwal @imAlan @ethanresnick @brentdur

### CODE REVIEW

**Comment by ethanresnick** [comment]
@maxdumas Good call on the max length. I'll try to figure out what's going on there... it's probably something in the underlying json-api lib, not the api repo.

**Comment by AbhiAgarwal** [comment]
@maxdumas Looks good to me! I tested it on my local machine and I can do the whole CRUD. When it's merged with develop we have a staging version setup here (http://intranet-staging.tnyu.org/). So we can all test to see if it's ready to be pushed into the master yet!

**Comment by maxdumas** [comment]
Thanks guys! Merging and will do more testing on the staged version. @ethanresnick let me know if there's anything that needs to be done on my end.

**Comment by AbhiAgarwal** [comment]
Staged version should be up now :D

**Comment by ethanresnick** [comment]
@maxdumas Ok, I fixed the maxlength issue. When the api is next deployed (and the json-api lib is updated), things should work.

**Pull request merged**
