### PR TITLE
List view: update url on changing selected model

### PR DESCRIPTION
**Pull request by ethanresnick**
This is my attempt at fixing #85. Again, I have no clue if I'm doing it right, so @maxdumas, please show me the angular wayz.

### CODE REVIEW

**Comment by maxdumas** [comment]
@ethanresnick While this certainly works, by using `$state.go` you are effectively going to a new page. While this doesn't incur any bad stuff in terms of templating or anything, it *does* result in a new request to the API to refresh the list data every time the selection is changed. This isn't really your fault, and ideally it would go away with the completion of #96 but either way it might be better to more directly alter the URL rather than causing a state transition, because going to a new page every time you choose a new thing definitely doesn't seem to be the best way to do that. Using the `$location` service to driectly modify the URL might be a better way to go about this.

**Comment by ethanresnick** [comment]
@maxdumas Using `$location` does make the back button work correctly, right? If so, then the only other concern I'd have with that is: it seems like using `$location` would mean that angular `ui-router`'s representation of the current state (params) is incorrect/out of sync. Could that cause any problems? Is there a way to change a param of the current state without triggering a `$state.go`?

**Comment by maxdumas** [comment]
@ethanresnick You were right, `$location` didn't work with history, which was unsurprising. I found a better way to do it, however. Using the lower level method `$state.transitionTo` gives us the option to update the state without refreshing the view, which actually works phenomenally. It works with history and the controller even seems to get the updated parameters. So all is well!

**Comment by ethanresnick** [comment]
@maxdumas Awesome!

**Comment by AbhiAgarwal** [comment]
:+1:

**Pull request merged**
