### PR TITLE
Total Rewrite!

### PR DESCRIPTION
**Pull request by maxdumas**
We've got everything working except the wizard, ironically, but the entire API is mapped! :D

# DO NOT DELETE THIS BRANCH WHEN MERGING THIS PR.

### CODE REVIEW

**Comment by AbhiAgarwal** [comment]
@clay-reed-a Have you done a code-review!

**Comment by clay-reed-a** [comment]
I am working on one right now! Clay a

**Comment by maxdumas** [comment]
Any update on this guys? Let's get this out there!

**Comment by AbhiAgarwal** [comment]
I'm doing :+1: on this! I've looked through the code, and it seems well written. Just to add in comments about what each thing means. We'll establish that in the next release.

**Comment by maxdumas** [comment]
Sweet! Yeah I agree, it definitely needs better commenting. Also unit tests. Of course those are the two things that can always be put off ;P

Do you want to attempt merging this? It's definitely gonna be best to just do `git rebase` + `git merge --no-ff` since we basically rewrote everything and there are merge conflicts.

**Pull request merged**
