### PR TITLE
Dynamically configure Tinymce

### PR DESCRIPTION
**Pull request by ethanresnick**
@maxdumas Can you please review this when you have a sec! In particular, I have no idea whether it's appropriate to have the form element provider return the config...I can imagine that it might be, but I can also imagine that logic living lower down, i.e. in some component that only applies to wysiwg fields. #teachmeanangular 

Other than that though, it seems to work

### CODE REVIEW

**Comment by maxdumas** [comment]
This looks great! That said, I do agree that this isn't the best place to put this logic; I would have made a separate "tinymce-input-ctrl.js" controller that handles all of this logic, that is then tied to the "tinymce-input" template. This is exactly how it is done with the date input, see [date-input.html](https://github.com/TechAtNYU/intranet/blob/develop/app/partials/inputs/date-input.html) and [date-ctrl.js](https://github.com/TechAtNYU/intranet/blob/develop/app/js/controllers/inputs/date-ctrl.js). I would just copy your configuration function into a controller for TinyMCE, attach it to `$scope`, and then just call that from the template.

I can do this if you want, but if you'd like you can take a crack at it too.

**Comment by ethanresnick** [comment]
@maxdumas I'll take a crack at this!

**Comment by ethanresnick** [comment]
@maxdumas Ok, I've updated the PR. Take a look!

**Comment by maxdumas** [comment]
Updated this to fit our linting/style requirements. Other than that, looks fantastic! Nice work.

**Pull request merged**
