### PR TITLE
Sort home page resource type cards in ABC order

### PR DESCRIPTION
**Pull request by ethanresnick**
cc @grungerabbit

@maxdumas: is this the right place for this?

### CODE REVIEW

**Comment by maxdumas** [comment]
Is there any externally-logical ordering that is imposed on the resources that the API returns already, or are they just returned in the order they are defined? If the former is true, then I think this logic should be moved to [the main controller](https://github.com/TechAtNYU/intranet/blob/master/app/js/controllers/main-ctrl.js). If it's the latter, maybe it might make more sense to have the API return the resources in some externally-logical ordering to begin with? I'm not sure what the stance of the JSON API spec is on implicit guaranteed ordering of collections, so it may or may not be appropriate to do it in the API. 

If the collection does not have an implicit order and the spec says that we should not depend on implicit ordering, then I'm fine with where this is. Although the PR should be into `develop`, not `master`. :)

**Comment by ethanresnick** [comment]
> Is there any externally-logical ordering that is imposed on the resources that the API returns already

The API returns them roughly in most-frequently-used order. I.e., the big/important resource types like Events and People come first, while non-important ones (like SchoolAttendance) come at the end. This is designed to make it easier for someone looking at the docs for the first time to get a sense of the API's major capabilities. But it's less ideal for someone who's looking for a particular resource type (e.g. TeamMembership), because it's hard to predict where in the list that type'll be; abc order solves that.

> I'm not sure what the stance of the JSON API spec is on implicit guaranteed ordering of collections, so it may or may not be appropriate to do it in the API.

JSON-API supports a `sort` query parameter that can take arbitrary values (i.e. the values can but don't need to correspond directly to resource field names), so any implicit ordering can always be made explicit/reliable for a contract just by adding that parameter. So, perhaps the docs url should be `api.tnyu.org/v2?sort=importance`. Then, we could have a different URI for `api.tnyu.org?sort=name.plural`. 

Defining these URIs on the API side probably makes the most sense long-term, though it would take (much) more logic to implement it there than it does to implement it on the client. Still, maybe it's worth doing. 

This conversation's actually gotten me thinking though...maybe we don't want to sort the home page in ABC order at all? I.e. if the advantage of ABC is just that it makes it easier to find a particular resource type by name, maybe we can just put a "Filter" text box at the top of the page and, as users type into that box, the cards for resource type whose names don't match their input just disappear? So, a user would type "T" and then only the "Teams" and "Team Memberships" cards would be left. This would let us get the benefits of most-important-ordering, namely, that Events and People can still come near the top, while also giving us most of the benefits of ABC ordering. (I say "most of" because typing in an input to filter is a bit less discoverable/requires more user effort than just having the cards sorted already.) Thoughts, @grungerabbit?

If we go that way, then we don't have to implement anything else on the API side. If we instead just show the cards in abc order upfront, then I think we could support that ordering on the API side (with `?sort`)... but that we should also support it on the client side, because, when we release the intranet as a library, I don't want every API that uses it to need to implement the `?sort` logic themselves—that seems like an implementation burden that we can pretty easily take away from other developers. In that case, I'd refactor this to put the logic in the main controller as @maxdumas suggests and resubmit it to `develop`.

**Comment by grungerabbit** [comment]
> Events and People can still come near the top...

So, ideally we would cut down the cards as described in the first part of #91. Only infra gets the massive list. Most members get 6 cards. That's small enough to see all cards at once.

And we fools in infrastructure can deal with cards in alphabetical order ;) seems like we have better uses of our time and energy than building a filter. Plus, you can always use cmd+F...

**Comment by maxdumas** [comment]
Picking up where we left off, I agree with @grungerabbit. I am fine with the the ordering being performed on the client side, as long as we move it to the main controller, because I think having it is better than not having it. Can you resubmit this PR to `develop` with that change @ethanresnick?

**Pull request closed without merging**
